language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install ply pep8 pylint coveralls .
script:
  - pep8 pyfranca
  - pylint --errors-only pyfranca
  - python setup.py check
  - coverage run --source=pyfranca setup.py test
after_success:
  coveralls
